package study.snacktrack.dto;

import lombok.Data;

/**
 * Data Transfer Object (DTO) providing comprehensive nutritional and serving information about a food item.
 * This detailed structure is typically used when fetching data from an external source for logging or detailed display to the user.
 */
@Data
public class ApiFoodResponseDetailed {

    private int id;
    private String name;
    private int calorie;
    private float protein;
    private float carbohydrates;
    private float fat;
    private float defaultWeight;
    private String servingSizeUnit;
    private String brandName;

    /**
     * Getters and setters for all DTO fields are automatically generated by the Lombok @Data annotation.
     * These methods provide standard access and modification capabilities for the detailed food data.
     */
}