package study.snacktrack.dto;

import lombok.Data;

/**
 * Data Transfer Object (DTO) used for carrying detailed nutritional information about a food item.
 * This object is typically used to structure data retrieved from an external API or database before being presented to the user.
 */
@Data
public class ApiFoodResponse {

    private int id;
    private String name;
    private int calorie;
    private float protein;
    private float carbohydrates;
    private float fat;
    private String brandName;
    private String quantity;

    /**
     * Getters and setters for all DTO fields are automatically generated by the Lombok @Data annotation.
     * These methods provide standard access and modification capabilities for the encapsulated food data.
     */
}