package study.snacktrack.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object (DTO) used for sending full comment details back to the client.
 * This structure includes metadata about the comment, the author, and the user's interaction status with the comment.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class CommentResponse {
    private int id;
    private int authorId;
    private String authorName;

    private String authorImageUrl;

    private String content;
    private int mealId;
    private int likesCount;

    @JsonProperty("isLiked")
    private boolean isLiked;

    /**
     * Getters, setters, and constructors are automatically generated by the Lombok annotations @Data, @AllArgsConstructor, and @NoArgsConstructor.
     * These methods provide standard access and modification capabilities for all comment-related fields.
     */
}