package study.snacktrack.dto;

import study.snacktrack.entities.Ingredient;

import lombok.Data;

/**
 * Data Transfer Object (DTO) used for carrying complete details of a single ingredient within a meal.
 * This object includes the recorded quantity and the nutritional data of the food source, which can be external or internal.
 */
@Data
public class IngredientResponse {

    private int id;
    private Float amount;
    private Float pieces;
    private ApiFoodResponseDetailed essentialApi;
    private EssentialFoodResponse essentialFood;

    /**
     * Default constructor required for Jackson serialization and deserialization.
     * This constructor allows the object to be instantiated without initial parameters.
     */
    public IngredientResponse() {
    }

    /**
     * Constructs an IngredientResponse object by mapping data from a persistent Ingredient entity.
     * This constructor simplifies the conversion process and ensures that related food data is initialized using its own DTO structure.
     *
     * @param ingredient The Ingredient entity to map data from.
     */
    public IngredientResponse(Ingredient ingredient) {
        this.id = ingredient.getId();
        this.amount = ingredient.getAmount();
        this.pieces = ingredient.getPieces();
        this.essentialApi = null;
        this.essentialFood = new EssentialFoodResponse(ingredient.getEssentialFood());
    }

    /**
     * Getters and setters for all DTO fields are automatically generated by the Lombok @Data annotation.
     * These methods provide standard access and modification capabilities for the ingredient's detailed properties.
     */
}