package study.snacktrack.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Data Transfer Object (DTO) used for carrying the result of a successful user login attempt.
 * This structure provides the necessary authorization token along with supplementary information regarding the user's account status.
 */
@Data
@AllArgsConstructor
public class LoginResponse {
    private String token;
    private boolean showSurvey;
    private String message;

    /**
     * Getters, setters, and constructors are automatically generated by the Lombok annotations @Data and @AllArgsConstructor.
     * These methods provide standard access and modification capabilities for the authentication token and related data.
     */
}