package study.snacktrack.dto;

import java.util.List;

import lombok.Data;

/**
 * Data Transfer Object (DTO) used for carrying the complete details of a Meal entity back to the client.
 * This structure includes the meal's descriptive data, the author, the main image, and a list of all component ingredients.
 */
@Data
public class MealResponse {

    private int id;
    private String name;
    private String description;
    private int authorId;
    private List<IngredientResponse> ingredients;
    private String imageUrl;

    /**
     * Getters and setters for all DTO fields are automatically generated by the Lombok @Data annotation.
     * These methods provide standard access and modification capabilities for the complete meal data structure.
     */
}