package study.snacktrack.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import study.snacktrack.entities.RegisteredAlimentation;
import study.snacktrack.entities.enums.MealNames;

/**
 * Data Transfer Object (DTO) used for carrying a detailed response about a logged food consumption entry.
 * This structure aggregates the consumed quantity, the meal time, and the full nutritional data of the item (either a simple food or a complex meal).
 */
@Data
@NoArgsConstructor
public class RegisteredAlimentationResponse {

    private int id;
    private int userId;
    private EssentialFoodResponse essentialFood;

    private ApiFoodResponseDetailed mealApi;

    private MealResponse meal;

    private String timestamp;
    private Float amount;
    private Float pieces;
    private MealNames mealName;

    /**
     * Constructs a RegisteredAlimentationResponse by mapping data from a persistent RegisteredAlimentation entity.
     * This constructor handles the conversion of internal entity data and initializes nested DTOs for the food or meal source.
     *
     * @param entry The RegisteredAlimentation entity to map data from.
     */
    public RegisteredAlimentationResponse(RegisteredAlimentation entry) {
        this.id = entry.getId();
        this.userId = entry.getUserId();
        this.timestamp = entry.getTimestamp().toString();
        this.amount = entry.getAmount();
        this.pieces = entry.getPieces();
        this.mealName = entry.getMealName();

        if (entry.getEssentialFood() != null) {
            this.essentialFood = new EssentialFoodResponse(entry.getEssentialFood());
        }

        if (entry.getMeal() != null) {
            MealResponse mDto = new MealResponse();
            mDto.setId(entry.getMeal().getId());
            mDto.setName(entry.getMeal().getName());
            mDto.setDescription(entry.getMeal().getDescription());
            mDto.setAuthorId(entry.getMeal().getAuthorId());
            mDto.setImageUrl(entry.getMeal().getImageUrl());
            this.meal = mDto;
        }
    }

    /**
     * Getters and setters for all DTO fields are automatically generated by the Lombok @Data annotation.
     * These methods provide standard access and modification capabilities for the registered alimentation entry details.
     */
}