package study.snacktrack.dto;

import lombok.Data;

/**
 * Data Transfer Object (DTO) used to represent a single item suggested for a user's shopping list.
 * This structure encapsulates the product's name, a brief description, and the suggested amount to purchase.
 */
@Data
public class ShoppingItem {
    private String name;
    private String description;
    private String quantity;

    /**
     * Getters and setters for all DTO fields are automatically generated by the Lombok @Data annotation.
     * These methods provide standard access and modification capabilities for the shopping item's details.
     */
}