package study.snacktrack.entities;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a record of a single "like" action applied by a specific user to a specific comment.
 * This entity is crucial for tracking user interactions and ensures that each user can only like a comment once, enforced by the unique constraint on the composite key.
 */
@Entity
@Table(name = "comment_likes", uniqueConstraints = {
        @UniqueConstraint(columnNames = { "user_id", "comment_id" })
})
@Data
@NoArgsConstructor
public class CommentLike {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(name = "user_id")
    private int userId;

    @ManyToOne
    @JoinColumn(name = "comment_id")
    private Comment comment;

    /**
     * Constructs a new CommentLike entity with the necessary foreign keys for creation.
     * This constructor is used when a user successfully submits a "like" for a comment.
     *
     * @param userId The ID of the user performing the like action.
     * @param comment The Comment entity being liked.
     */
    public CommentLike(int userId, Comment comment) {
        this.userId = userId;
        this.comment = comment;
    }

    /**
     * Getters and setters for all entity fields are automatically generated by the Lombok @Data annotation, except for the explicit constructor.
     * These methods provide standard access and modification capabilities for the CommentLike entity properties.
     */
}