version: '3.8'

services:
  mysql:
    container_name: guide-mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: snackTrackDB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    container_name: snacktrack-app
    build: .
    env_file:
      - .env
    image: snacktrack:latest
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/snackTrackDB
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_SQL_INIT_MODE: never
    restart: always
    volumes:
      - ./uploads:/app/uploads   # <--- podpinamy lokalny folder

volumes:
  mysql_data:
