spring.application.name=snackTrack

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/snackTrackDB
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.sql.init.mode=always
spring.sql.init.platform=mysql

spring.config.import=optional:file:.env[.properties]

fatsecret.client-id=8bea8ff2e257464ea2fc7146fa374540
fatsecret.client-secret=0b7033a1b8f943c482be76ff992a81b7