spring.config.import=optional:file:.env[.properties]

spring.application.name=snackTrack

spring.datasource.url=jdbc:mysql://${MYSQL_URL}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.sql.init.mode=never
spring.sql.init.platform=mysql

fatsecret.client-id=${FATSECRET_CLIENT_ID}
fatsecret.client-secret=${FATSECRET_CLIENT_SECRET}

gemini.api.key=${GEMINI_API_KEY}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
