# Ustawienia zrodla Danych (DataSource)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ustawienia JPA/Hibernate
# create-drop: tworzy schemat przy starcie i usuwa przy zamknieciu kontekstu (idealne do testow)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Opcjonalne: Wylacz inicjalizacje skryptow (np. data.sql), jesli chcesz tylko automatyczne DDL
spring.sql.init.mode=never
spring.jpa.show-sql=true